spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pizzaria?createDatabaseIfNotExist=true
    username: root
    password: 281105


  jpa:
    show-sql: true

server:
  error:
    include-stacktrace: never